### ISSUE TITLE
Klingt wie … 

### ISSUE THREAD

**Issue by skerbis** [eaCe/TAR#1]
https://gitlab.com/2062nandes/redaxo-mit-gultailker

😉

**Comment by eaCe** [comment]
Ha, das kannte ich noch nicht :)
Ich nutze allerdings kein docker oder gulp

**Comment by skerbis** [comment]
Habe gestern mal bei gitlab gestöbert und nach REDAXO Sachen gesucht. Da viel mir das ins Auge.

**Comment by eaCe** [comment]
https://bitbucket.org/myCodebox/ebfw/src/master/

Hier gibts ein altes Feuerwehr Addon :)

**Comment by skerbis** [comment]
Sachen gibts :-)
